### ISSUE TITLE
Error "Unexpected PLINK 1 .bed file size" when conducting fastGWA

### ISSUE THREAD

**Issue by potatoj210** [jianyangqt/gcta#101]
Hi Longda and the team,

I would like to report an issue when I was running --fastGWA-mlm. 

--fastGWA-mlm-binary 
--mbfile gwas_22.txt 
--grm-sparse sp_grm 
--pheno pheno0910.txt 
--qcovar qcovar.txt 
--covar covar.txt 
--threads 15 
--out ./GWAS/test2

Here is the  error I got:
Tuning parameters using null SNPs...
  reading 200 SNP...
Unexpected PLINK 1 .bed file size (expected 150062091618 bytes).

Based on the advices from Longda in a previous similar issue, I replaced "--mbfile" with "--bfile" and run them on each chromosome. However, it turns out that none of the chromosomes are causing the error. In other words, it seems that the command only run successfully with "--bfile".

Could you please provide any insights into why this might be happening? Any guidance would be greatly appreciated.

Best wishes,
Qianshu Ma

**Comment by longmanz** [comment]
Hi Qianshu,
Thank you for the information. This is a bit strange. Have you checked if you are using the version that is compatible with your linux system? We have compiled several versions for different linux kernel (https://yanglab.westlake.edu.cn/software/gcta/#Download)

**Comment by potatoj210** [comment]
Hi Longda,
Thank you very much for your advice. Yes, it is a little bit strange. I have checked the version and I am using this version: [gcta-1.94.1-linux-kernel-3-x86_64]. I will try other versions and see how it works.

Best wishes,
Qianshu

**Comment by potatoj210** [comment]
Hi Longda and all concerned,

I had good news to share - I finally identified the cause of the error I was facing. It occurred because the sample sizes of each chromosome file were different, as some individuals were excluded during QC.

I came across a note on the GCTA website (https://yanglab.westlake.edu.cn/software/gcta/#MakingaGRM) which says:
"Note: All these files shall have the same sample size and order. The program will prompt an error if not."
Unfortunately, I missed this detail.

For anyone encountering the same issue, please note that this error will arise if the sample sizes for each chromosome file differ when using the --mbfile.

Best wishes,
Qianshu

**Comment by longmanz** [comment]
Hi Qianshu, thank you for noticing this detail and getting back to us! This is definitely useful information to other users as well (which I also overlooked).
