### ISSUE TITLE
Warning message running on fastGWA-mlm

### ISSUE THREAD

**Issue by TinaNeik339** [jianyangqt/gcta#107]
Hi GCTA developers,

May I know if the fastGWA is running on MLM? 

There is a Warning message that says: the estimate of Vg is not statistically significant (i.e., p > 0.05). This is likely because the number of closely related individuals in the sample is not large enough. 
In this case, the program will use **linear regression for association test.**

Here is the command line that I used:

(base) Tinas-MacBook-Pro-2:gcta-1.94.2-MacOS-ARM-x86_64 tinaneik$ ./gcta64 --mbfile /Users/tinaneik/Downloads/gcta-1.94.2-MacOS-ARM-x86_64/geno_chrs_acephala_367_new_genotype.txt --grm-sparse sp_grm_acephala_367_new_genotype --fastGWA-mlm --pheno /Users/tinaneik/Downloads/acephala_235_samples_new_genotype_TFWphenotype_forGCTA.txt --qcovar /Users/tinaneik/Downloads/fixed_acephala_235_samples_new_genotype_forGCTA_PCA.eigenvec.txt --out acephala_gcta_367_tfw_fastGWA
*******************************************************************
* GCTA (Genome-wide Complex Trait Analysis)
* Version v1.94.1 Mac
* (C) 2010-present, Yang Lab, Westlake University
* Please report bugs to Jian Yang jian.yang@westlake.edu.cn
* MIT License
*******************************************************************
Analysis started at 15:28:13 +08 on Wed Nov 13 2024.
Hostname: Tinas-MacBook-Pro-2.local

Options: 
 
--mbfile /Users/tinaneik/Downloads/gcta-1.94.2-MacOS-ARM-x86_64/geno_chrs_acephala_367_new_genotype.txt 
--grm-sparse sp_grm_acephala_367_new_genotype 
--fastGWA-mlm 
--pheno /Users/tinaneik/Downloads/acephala_235_samples_new_genotype_TFWphenotype_forGCTA.txt 
--qcovar /Users/tinaneik/Downloads/fixed_acephala_235_samples_new_genotype_forGCTA_PCA.eigenvec.txt 
--out acephala_gcta_367_tfw_fastGWA 

Reading PLINK sample file from [/Users/tinaneik/Downloads/plink_mac_20231211/acephala_367_new_genotype_chr1_modified.fam]...
367 individuals to be included from the sample file.
Checking other sample files...
  All the files checked are OK.
Reading phenotype data from [/Users/tinaneik/Downloads/acephala_235_samples_new_genotype_TFWphenotype_forGCTA.txt]...
367 overlapping individuals with non-missing data to be included from the phenotype file.
367 individuals to be included. 0 males, 0 females, 367 unknown.
Reading PLINK BIM file from [/Users/tinaneik/Downloads/plink_mac_20231211/acephala_367_new_genotype_chr1_modified.bim]...
1019734 SNPs to be included from BIM file(s).
Reading PLINK BIM file from [/Users/tinaneik/Downloads/plink_mac_20231211/acephala_367_new_genotype_chr2_modified.bim]...
2217800 SNPs to be included from BIM file(s).
Reading PLINK BIM file from [/Users/tinaneik/Downloads/plink_mac_20231211/acephala_367_new_genotype_chr3_modified.bim]...
3736907 SNPs to be included from BIM file(s).
Reading PLINK BIM file from [/Users/tinaneik/Downloads/plink_mac_20231211/acephala_367_new_genotype_chr4_modified.bim]...
4771829 SNPs to be included from BIM file(s).
Reading PLINK BIM file from [/Users/tinaneik/Downloads/plink_mac_20231211/acephala_367_new_genotype_chr5_modified.bim]...
5619070 SNPs to be included from BIM file(s).
Reading PLINK BIM file from [/Users/tinaneik/Downloads/plink_mac_20231211/acephala_367_new_genotype_chr6_modified.bim]...
6688977 SNPs to be included from BIM file(s).
Reading PLINK BIM file from [/Users/tinaneik/Downloads/plink_mac_20231211/acephala_367_new_genotype_chr7_modified.bim]...
8010934 SNPs to be included from BIM file(s).
Reading PLINK BIM file from [/Users/tinaneik/Downloads/plink_mac_20231211/acephala_367_new_genotype_chr8_modified.bim]...
9102586 SNPs to be included from BIM file(s).
Reading PLINK BIM file from [/Users/tinaneik/Downloads/plink_mac_20231211/acephala_367_new_genotype_chr9_modified.bim]...
10180389 SNPs to be included from BIM file(s).
Reading quantitative covariates from [/Users/tinaneik/Downloads/fixed_acephala_235_samples_new_genotype_forGCTA_PCA.eigenvec.txt].
5 covariates of 367 samples to be included.
367 overlapping individuals with non-missing data to be included from the covariate file(s).
Reading the sparse GRM file from [sp_grm_acephala_367_new_genotype]...
After matching all the files, 367 individuals to be included in the analysis.
Estimating the genetic variance (Vg) by fastGWA-REML (grid search)...
Iteration 1, step size: 5.08899, logL: -1240.44. Vg: 0, searching range: 0 to 5.08899
Iteration 2, step size: 0.339266, logL: -1240.44. Vg: 0, searching range: 0 to 0.339266
Iteration 3, step size: 0.0226177, logL: -1240.44. Vg: 0, searching range: 0 to 0.0226177
Iteration 4, step size: 0.00150785, logL: -1240.44. Vg: 0, searching range: 0 to 0.00150785
Iteration 5, step size: 0.000100523, logL: -1240.44. Vg: 0, searching range: 0 to 0.000100523
Iteration 6, step size: 6.70155e-06, logL: -1240.44. Vg: 0, searching range: 0 to 6.70155e-06
Iteration 7, step size: 4.4677e-07, logL: -1240.44. Vg: 0, searching range: 0 to 4.4677e-07
Iteration 8, step size: 2.97847e-08, logL: -1240.44. Vg: 0, searching range: 0 to 2.97847e-08
Iteration 9, step size: 1.98564e-09, logL: -1240.44. Vg: 0, searching range: 0 to 1.98564e-09
Iteration 10, step size: 1.32376e-10, logL: -1240.44. Vg: 1.32376e-10, searching range: 0 to 2.64753e-10
Iteration 11, step size: 1.76502e-11, logL: -1240.44. Vg: 5.29505e-11, searching range: 3.53003e-11 to 7.06007e-11
Iteration 12, step size: 2.35336e-12, logL: -1240.44. Vg: 5.88339e-11, searching range: 5.64805e-11 to 6.11873e-11
Iteration 13, step size: 3.13781e-13, logL: -1240.44. Vg: 5.71081e-11, searching range: 5.67943e-11 to 5.74219e-11
fastGWA-REML converged.
logL: -1240.44
Sampling variance/covariance of the estimates of Vg and Ve:
 1102.38 -1018.03
-1018.03  1492.95

Source	Variance	SE
Vg	5.71081e-11	33.202
Ve	318.062	38.6387
Vp	318.062

Heritability = 1.7955e-13 (Pval = 1)
fastGWA-REML runtime: 0.600172 sec.
Warning: the estimate of Vg is not statistically significant (i.e., p > 0.05). This is likely because the number of closely related individuals in the sample is not large enough. 
In this case, the program will use linear regression for association test.

Performing fastGWA linear regression analysis...
fastGWA results will be saved in text format to [acephala_gcta_367_tfw_fastGWA.fastGWA].
  Filtering out variants with MAF < 0.0001, or customise it with --maf flag.
  Filtering out variants with missingness rate > 0.10, or customise it with --geno flag.
  100% finished in 22.0 sec
10180389 SNPs have been processed.
Saved 10052506 SNPs.

Analysis finished at 15:28:44 +08 on Wed Nov 13 2024
Overall computational time: 31.93 sec.

**Comment by longmanz** [comment]
Hi,
If you see `In this case, the program will use linear regression for association test.` then it means that fastGWA has switched to linear regression instead of MLM. According to your log file, your sample size is too small and it is not recommended to use fastGWA in this case. You may consider using GCTA-MLMA or GCTA-LOCO (https://yanglab.westlake.edu.cn/software/gcta/#MLMA).
