### ISSUE TITLE
Weighted regression

### ISSUE THREAD

**Issue by DrGengWang** [jianyangqt/gcta#108]
Hi,

Is there an option in GCTA to run a weighted GWAS? If not, would it be possible to implement this feature in a future update? I believe it would be a valuable addition to the program.

I attempted to estimate heritability and variances using the --reml option along with --reml-res-diag. My understanding is that --reml-res-diag specifies the diagonal elements of the residual correlation matrix in REML (for weighting purposes). It worked fine.

I then ran the GWAS using --mlma with the --reml-res-diag option in GCTA. However, it appears that --reml-res-diag did not affect the regression. Unfortunately, there was no error or warning indicating that the command was ignored, and the results were identical to those of the "unweighted" analysis. It would be helpful if the program provided a warning or notification when --reml-res-diag is not applied.

Thank you!

**Comment by longmanz** [comment]
Hi, 
--reml-res-diag only works with GREML analysis at the moment. Thank you for the suggestion. We will consider implementing it in the future.
