### ISSUE TITLE
POLMM (Proportional Odds Logistic Mixed Model) approaches in GCTA

### ISSUE THREAD

**Issue by Shicheng-Guo** [jianyangqt/gcta#12]
Dear Prof. Yang, 

I am wondering whether POLMM is included in fastGWA-LMM or not so that categorical outcome can be tested. 

POLMM (Proportional Odds Logistic Mixed Model) approaches are designed for ordinal categorical data analysis in large cohort studies. 

Thanks. 

Shicheng

**Comment by longmanz** [comment]
Hi Shicheng,

POLMM is not included in GCTA-fastGWA. 

Best,
Longda
