### ISSUE TITLE
Is it possible to run gcta on two different sets of summary statistics

### ISSUE THREAD

**Issue by isabelleboothman** [jianyangqt/gcta#14]
Hi, 
I have summary statistics for two gwas and I want to calculate the heritability between the two is it possible to do this with GCTA?

Thanks,
Isabelle Boothman

**Comment by longmanz** [comment]
Hi, 
GCTA-GREML only supports calculating heritability (h2) based on individual genotype/phenotype data. For computing h2 using summary data please try using LD score regression (https://github.com/bulik/ldsc).
