### ISSUE TITLE
Error:   invalid option "--grm-sparse".

### ISSUE THREAD

**Issue by Malane19** [jianyangqt/gcta#22]
Hi,

I am trying to run a --fastGWA-mlm-binary for a dataset of 292 individuals and 48026 SNPs.  I don`t have a pedigree so I am running the lines:
gcta64 --bfile geno --make-grm --thread-num 10 --out geno_grm
gcta64 --grm geno_grm --make-bK-sparse 0.05 --out sp_grm to create the sparse GRM, which is running perfectly and saving GRM sparse (2170 pairs) to [sp_grm.grm.sp], but when I try to run the --fastGWA-mlm-binary, by to following line: 
gcta64 --bfile ./geno --grm-sparse ./sp_grm --fastGWA-mlm --covar ./covar_lactation_farm_season --pheno ./pheno_code_0_1 --thread-num 10 --out glmm_assoc, i have the following output:

#######################################
Analysis started at 14:14:13 EDT on Wed Jul 06 2022.
Hostname: XXX

Accepted Options:
--bfile geno
--make-grm
Error:
invalid option "--sparse-cutoff".

An error occurs, please check the options or data.
##################################################################

I would like to understand why I am having this problem and how to solve this problem. I appreciate any help.

Thanks in advance,

Maria

**Comment by RL-m** [comment]
Hi Maria,
I met the same problem as yours before. I was using 1.93 beta version. But when I updated to the latest version (1.94.1) the problem was solved. Maybe you can check which version of GCTA you used.
Ruilei

**Comment by Malane19** [comment]
Hi Ruilei,

Thank you so much for helping with that. You are right, when I updated GCTA to the version (1.94.1) it worked.

thanks,
Maria

**Comment by benjaminfang** [comment]
closed because it was solved.
