### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by maxozo** [jianyangqt/gcta#26]
Hi, 
I got a segmentation fault with a chr3, but not any other chromosomes. Can developers please help with this.
The issue is very similar to the one described on the forum - https://gcta.freeforums.net/thread/604/segmentation-fault-cojo-slct  
Delving down to the issue I can see that the gcta doesnt like some betas for some reason, but if they are run independently then it works. I am not sure what could be the issues, hoping you could comment.

**Comment by maxozo** [comment]
Hi, thanks for such a prompt reply. I have generated a small 1kb region plink/cojo input files that I fail to run. (i know I should use the full plink but this still gives the same error if a full bfile is provided with full _sum cojo file).

I would initially calculate the frequencies and generate a GWAS summary stats specific plink file by:

`plink --bfile path/to/bfile/plink_genotypes/plink_genotypes --extract path/to/snp/list/rs9958650.snp.list --maf 0.0001 --make-bed --freqx --out /pat/to/new/plink/loc/plink/rs9958650`

I would then calculate the FREQ value in R by:

`          freqs$FreqA1=(freqs$'C(HOM A1)'*2+freqs$'C(HET)')/(2*(rowSums(freqs[,c("C(HOM A1)", "C(HET)", "C(HOM A2)")])))
          outcome2$FREQ=freqs$FreqA1[match(outcome2$variant_id,freqs$SNP)]
          idx=which(outcome2$effect_allele!=freqs$effect_allele)
          outcome2$FREQ[idx]=1-outcome2$FREQ[idx]
          # outcome2$se=sqrt(outcome2$varbeta)
          Cojo_Dataframe=outcome2[,c("variant_id","effect_allele","other_allele","FREQ","beta","standard_error","p_value","N")]
          names(Cojo_Dataframe)=c("SNP" , "A1" ,  "A2"  , "freq", "b"  ,  "se" ,  "p" ,   "N")`

Then I am trying to find the independent snps in a particular region and condition signal based on this. But the independent SNP part fails on the chr3 (tested on other chromosomes with a fll file and it works, but this doesnt).

`gcta_v1.94.0Beta_macOS/gcta_v1.94.0Beta_macOS --bfile /path/to/bed/file/rs9958650 --cojo-p 1e-4 --extract /path/to/bed/file/rs9958650.snp.list --cojo-file /path/to/bed/file/rs9958650_sum.txt --cojo-slct --out path/to/output/rs9958650_step1`

To understand the error I have tried to find the first SNP that makes the above fail. I have attached the file in zip [test.zip](https://github.com/jianyangqt/gcta/files/9149934/test.zip) and if last SNP deleted the cojo works. Otherwise it fails.
To see if its with the version or a setup of my device I have tested it on mac and linux and with different versions, all give same error. Changing the b slightly again resolves the issue, but I dont want to change betas of my files. 

Any suggestion on how to resole this, or what I am doing wrong would be much appreciated. Thank you.

**Comment by maxozo** [comment]
Hi, any updates re what could be causing this issue? Thanks!

**Comment by benjaminfang** [comment]
Hi, maxozo.
It's a bug, and thank you for your information.
We fix this recently, and you can download the bug-fix version GCTA here: https://github.com/jianyangqt/gcta/releases/tag/v1.94.1beta

Any problem please contact us.

**Comment by maxozo** [comment]
Excellent! Thank you @benjaminfang . This seems to have resolved the issue.

**Comment by benjaminfang** [comment]
Since no now problem emerged, I closed this issue.

**Comment by EyadElbahtety829** [comment]
Hello Benjamin, 

I recently incurred the same error with the current GCTA version v. 1.94.1. At Chr. 3 it shows a segmentation error. Any way around that? 

Many thanks

**Comment by benjaminfang** [comment]
Hi Eyad,

Is the binary you used the latest one provided at https://yanglab.westlake.edu.cn/software/gcta/#Download? If so, what is the distribution and kernel version of the Linux you are using?

Regards,
Ben

**Comment by EyadElbahtety829** [comment]
Hell Ben,

Thanks for your prompt response! 
I am working on a computer cluster with kernel version: 4.18.0-425.3.1.el8.x86_64 and distribution Rocky Linux release 8.7 (Green Obsidian) PLATFORM_ID="platform:el8".

Many thanks,
Eyad

**Comment by benjaminfang** [comment]
Dear Eyad,

Please try this binary which compiled on Linux running kernal v4.
https://yanglab.westlake.edu.cn/software/gcta/bin/gcta-1.94.1-linux-kernel-4-x86_64.zip

Regards,
Ben

**Comment by EyadElbahtety829** [comment]
Hello Ben,

I have tried it but apparently it is the same version we have on HPC. It produced the same segmentation error at the same place once again. I am now trying to run on my local computer using the MacOS version but obviously it is taking much longer, I will report back here for others when it finishes. In the mean time, any other suggestions?

Many thanks,
Eyad

**Comment by EyadElbahtety829** [comment]
Update - using GCTA v.1.24.7 has worked for me without any other modifications. It would be best if this can be fixed as well in the new versions somehow. I will keep using that version for the time being.

**Comment by benjaminfang** [comment]
Thank you for the update on the message. Our college will look into this issue and address it in the future.
