### ISSUE TITLE
Issues installing GCTA on mac

### ISSUE THREAD

**Issue by anne0113** [jianyangqt/gcta#39]
Hi, 

I'm trying to install GCTA on a mac. I unzipped it via the terminal and tried to load it, but am getting 'no such file or directory'. Does anyone have any suggestions on how to fix this? 
<img width="518" alt="Screenshot 2023-04-29 at 7 57 35 PM" src="https://user-images.githubusercontent.com/132175219/235328842-dc5a2149-9777-4a99-8984-ef26161d5ddb.png">

**Comment by longmanz** [comment]
Hi, 
Installing GCTA on Mac will be tricky as many dependencies are required. We recommend users to directly use the pre-compiled GCTA for Mac at https://yanglab.westlake.edu.cn/software/gcta/index.html#Download.

**Comment by CreRecombinase** [comment]
The binary file name is `gcta-1.94.1`, not `gcta64`
