### ISSUE TITLE
What should input files look like?

### ISSUE THREAD

**Issue by sanjaynagi** [jianyangqt/gcta#54]
A colleague is trying to use FastGWA-GLMM, but there is no documentation on what the covar/qcovar files should look like?

**Comment by sanjaynagi** [comment]
Just realised that it probably follows Plink. but please explain this more in the docs.

**Comment by longmanz** [comment]
Hi,
The basic input format of the covar/qcovar for all modules in GCTA (including FastGWA) is actually posted here (https://yanglab.westlake.edu.cn/software/gcta/index.html#Inputandoutput). It is slightly different from Plink, so please be cautious about it.

**Comment by sanjaynagi** [comment]
I can’t see anything about covar or qcovar on that page? On 11 Aug 2023, at 18:40, Longda ***@***.***> wrote:﻿
Hi,
The basic input format of the covar/qcovar for all modules in GCTA (including FastGWA) is actually posted here (https://yanglab.westlake.edu.cn/software/gcta/index.html#Inputandoutput). It is slightly different from Plink, so please be cautious about it.

**Comment by longmanz** [comment]
Hi,
There are 2 links. The covar/qcovar is posted in the 2nd one.
