### ISSUE TITLE
phenotype file not found in fastGWA

### ISSUE THREAD

**Issue by Wenxi-Zhang** [jianyangqt/gcta#55]
Hello,

In the fastGWA example, my command:
 ./gcta-1.94.1 --grm-sparse test_sp_grm --fastGWA-mlm --pheno test.phen --out geno_assoc 
which modified from this command: 
<img width="501" alt="image" src="https://github.com/jianyangqt/gcta/assets/83405608/90285040-26a5-488e-b6d3-c1c9c7ff4a6f">
I got this:
--grm-sparse test_sp_grm 
--fastGWA-mlm 
--pheno test.phen 
--thread-num 10 
--out geno_assoc 
The program will be running with up to 10 threads.
**Error: no phenotype file found.**

Under the current directory I have a phenotype file named “test.phen”. When I tried this command:
gcta64 --grm test --pheno test.phen --reml --out test --thread-num 10 
in estimating the variances, “--pheno test.phen” works. 

How can I deal with this issue?

**Comment by longmanz** [comment]
Hi,
You need to input the genotype file using either "--bfile" or "--mbfile". 
But it is true the error message seems to be mis-leading here. Thank you for reporting this. We will fix it.
