### ISSUE TITLE
sample_subset is not in strictly increasing order

### ISSUE THREAD

**Issue by ZhangZhenYang-zzy** [jianyangqt/gcta#63]
When I conduct GWAS by --fastGWA-mlm, it report "sample_subset is not in strictly increasing order", and cannot go on . Can you tell me how to solve it?

![微信图片_20231219134826](https://github.com/jianyangqt/gcta/assets/33117253/274d47f6-8bca-47c3-8547-e8f52014c36f)

**Comment by longmanz** [comment]
Hi, 
I guess you are using Plink PGEN format. It seems to be related to your --covar/qcovar file or --pheno file. The individuals listed in them should be in the same order as in your genotype .fam file. This is required by the Plink2 PgenReader (not GCTA), and I can barely found info about this error at (https://github.com/BertrandServin/pgenlib/blob/master/README.md).
