### ISSUE TITLE
Inquiry about the LD window size setting in the GSMR via GCTA tool

### ISSUE THREAD

**Issue by laleoarrow** [jianyangqt/gcta#81]
Hi all, I see that there is `--clump-r2 0.05` flag to set the r2 cutoff but I did not found the flag to set LD window size.  Does the window size setting for clumping in GSMR are not changeable? If so, what is the default setting? (e.g., 1MB? 500KB?)

**Comment by anglixue** [comment]
Hi,
You can use flag `clump_wind_size` to change the clumping LD window size. The unit is kb and the default setting is 1000 (i.e., 1Mb).
Let me know if it works for you. Thanks!

Angli

**Comment by laleoarrow** [comment]
This should get me going! Thank you for clarifing this!

**Comment by pjawinski** [comment]
Hi everyone,

I was exploring the options for the precompiled Linux executables and discovered that the flag `--clump-kb` can be used for this purpose.

Just thought I'd share in case anyone else finds it useful!
