### ISSUE TITLE
--fastGWA-mlm: Unexpected PLINK 1 .bed file size at tuning parameter step

### ISSUE THREAD

**Issue by acannis** [jianyangqt/gcta#86]
Hi Longda and team,

I'm trying to run --fastGWA-mlm with the following options:

~/gcta-1.94.1-linux-kernel-3-x86_64/gcta64 \
--mbfile dosageFiles_chrom1-22_list.txt \
--grm-sparse sparseGRM \
--fastGWA-mlm \
--pheno phenotypes.txt \
--qcovar quantitative_covariates.txt \
--covar  categorical_covariates.txt \
--threads 10 \
--save-fastGWA-mlm-residual \
--out outFile

My dosage files are for 10,000 UKB white British related individuals, and my sparseGRM file is also made from these individuals' genotypes filtered to MAF>0.01.

When I reach the pruning step, I receive the following error: 

Tuning parameters using 2000 null SNPs...
  reading genotypes...
Unexpected PLINK 1 .bed file size (expected 20990642503 bytes).

I've tried remaking the dosage files and the sparseGRM matrix, and nothing seems to be working. I've also run similar analyses on non-related individuals and they worked fine, which makes me wonder if it has something to do with the relatedness? The heritability information is:

Sampling variance/covariance of the estimates of Vg and Ve:
 1.31765e-05 -1.15653e-05
-1.15653e-05  1.41396e-05

Source  Variance        SE
Vg      0.0268749       0.00362995
Ve      0.116785        0.00376027
Vp      0.14366

Heritability = 0.187073 (Pval = 1.32489e-13)
fastGWA-REML runtime: 0.158552 sec.

I appreciate any guidance you can give on this error!
Best,
Aubrey

**Comment by longmanz** [comment]
Hi Aubrey,
Thank you for reporting this. Can you try to run gcta with the same genotype files but on each chromosome individually (i.e., using `--bfile` instead of `--mbfile`)? It seems that some of the plink files are not synced correctly so we will need to pinpoint which chromosome is causing the issue.

**Comment by acannis** [comment]
Hi Longda,

I tried rerunning by individual chromosomes using the --bfile command. This helped me identify errors for two autosome plink files and my chromosome X plink file. After recreating the autosome plink files, they ran fine. 

I still had some trouble with chromosome X, but your vignette [here](https://yanglab.westlake.edu.cn/software/gcta/#fastGWA) helped me run it successfully in two steps. I still needed to run each chromosome individually, but when I did that it worked fine.

Thanks you for your help!
Aubrey

**Comment by longmanz** [comment]
Hi Aubrey, 
Glad to hear that the 2-step strategy works. According to your information, I am guessing the chrX contains some individuals with high missing rates (or some of the individuals are missing), therefore when loading all chromosomes simultaneously it will lead to error. 
Please feel free to reopen the issue if the problem re-occurs.
