### ISSUE TITLE
--mpheno flag not working in gcta v1.94.1

### ISSUE THREAD

**Issue by RPorneso** [jianyangqt/gcta#88]
I get this error when I tried using the --mpheno flag. I tried different iterations to make sure I just wasn't committing a syntax error. The following versions result in similar errors shown in the below screenshot.

--mpheno 3 pheno.txt without the --reml-pred-rand flag
--mpheno pheno.txt 3 with and without the --reml-pred-rand flag (results in "invalid option 3")

![image](https://github.com/user-attachments/assets/749c7728-98d7-4b6d-9100-aef513cbb4ac)

I have ended up running the below 3 times creating 3 different files for my 3 phenotypes (these are the same outcome variables but taken from different time points). I am using GCTA to get the GBLUP as a first step before running a full mean and variance GWAS on the residualized phenotype controlling for non independence.

I am running this bash script in a Linux HPC. Thanks in advance for your attention.

**Comment by longmanz** [comment]
Hi,
The `--mpheno` only works when you provide a `--pheno` flag. So the correct syntax would be:
`./gcta ... --pheno pheno.txt --mpheno 3 ...`. 
Please re-open the issue if the issue persists and we will look into this further.
