### ISSUE TITLE
Error:    invalid option "--fastGWA-lr".

### ISSUE THREAD

**Issue by Hannah430** [jianyangqt/gcta#90]
Hi, 

I am trying to use --fastGWA-lr and --envir to assess linear regression-based analysis with the following code:

```
module load StdEnv/2020
module load gcc/9.3.0
module load gcta/1.93.2
gcta64 --bfile test_chr22 \
       --fastGWA-lr \
       --pheno gcta_pheno_test.txt \
       --qcovar gcta_qcovar_test.txt \
       --covar gcta_covar_cat_test.txt \
       --envir gcta_env_test.txt \
       --thread-num 10 \
       --out test_chr22
```

However, i kept on getting an Error of invalid option "--fastGWA-lr". I realized that this issue only arise when I add --envir in the code. Is there anything i can do to fix this issue? 

Thank you!
Hannah

**Comment by longmanz** [comment]
Hi Hannah,
Please try to use the latest version of GCTA (v1.94.1). The --envir test is not available with the current version you are using. You can easily download the executable  from https://yanglab.westlake.edu.cn/software/gcta/#Download .

Feel free to re-open this thread if you encounter any issue with v1.94.1

**Comment by Hannah430** [comment]
Hi, 

Thank you! I have downloaded [gcta-1.94.1-linux-kernel-3-x86_64.zip](https://yanglab.westlake.edu.cn/software/gcta/bin/gcta-1.94.1-linux-kernel-3-x86_64.zip), 
however, there's still an error message:
Error: 
  invalid option "--envir".

Is there anything I should do on my end to fix this issue?

Thank you!
Hannah
