### ISSUE TITLE
Regarding the issue of default data filtering in FastGWA

### ISSUE THREAD

**Issue by yuxizhang01** [jianyangqt/gcta#97]
Hello,
When performing GWAS analysis using FastGWA in GCTA, my input genotype data contains 60 million SNPs. However, after automatic filtering with the default parameters, only about 40 million SNPs remain. I tried to resolve this by relaxing the missing rate cutoff, but since the cutoff cannot be greater than or equal to 1, some SNPs are still being filtered out.

Are there any parameters that allow for no data filtering during GWAS, and instead perform pure association analysis, or are there other methods to retain all of my SNPs?

Attached is a screenshot of my standard output.
![微信图片_20240906091811](https://github.com/user-attachments/assets/716be6b7-c5cf-4b70-a874-129d803bc2a8)

**Comment by longmanz** [comment]
Hi, 
You can use flag `--nofilter` to mute any filtering steps (which is equivalent to `--maf 0 --geno 0`). Note that the `--geno` flag indicates the genotyping rate, so if you set it to `--geno 0.99999` it will filter out all those variants with genotyping rate less than 0.99999. That is probably the reason why some variants are missing in your analysis.
